#!/bin/zsh
is_up () {
    local up=1 ;
    for interface in eth0 wlan0 ; do
        if (/sbin/ifconfig $interface | egrep "(UP|RUNNING)" > /dev/null) 
            then up=0 ;
        fi ;
    done;
return $up ;
}

if [ -x /usr/bin/git -a -d $HOME/.git -a is_up ]
then cd $HOME && /usr/bin/git pull && cd -
fi

# Color syntax
git config color.ui true

