#!/bin/zsh
# stderr in red
{ { exec 1>&3 } 2>&1 | while read line; do print '\e[91m'${(q)line}'\e[0m'; done } 3>&1    
#exec 2>>(while read line; do
#  print '\e[91m'${(q)line}'\e[0m' > /dev/tty; done &)


