#!/bin/zsh

#############
# Les alias #
#############

# Gestion du 'ls' : couleur & ne touche pas aux accents
alias ls='ls --classify --tabsize=0 --literal --color=auto --show-control-chars --human-readable'

# Alias xals
[[ -x /usr/bin/colorgcc ]] && alias gcc="colorgcc"
[[ -x /usr/bin/colormake ]] && alias make="colormake"
[[ -x /usr/bin/aptitude ]] && alias aptitude="aptitude --disable-columns"

# Demande confirmation avant d'écraser un fichier
alias cp='cp --interactive'
alias mv='mv --interactive'
#alias rm='rm --interactive'

# Raccourcis pour 'ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias llm='ls -la | most'

# Quelques alias pratiques
alias less='less --quiet'
alias df='df --human-readable'
alias du='du --human-readable'
alias m='mutt -y'
alias md='mkdir'
alias rd='rmdir'
alias upgrade='aptitude update && aptitude full-upgrade && apt-get clean'

#alias persos
alias nano='nano -miA'
alias cd..='cd ..'
alias addnote='bash ~/.conky/notes.sh'
alias empty-trash='sudo rm -r /home/maethor/.local/share/Trash/files/*'

#alias de compilations
alias compilegtk='gcc $(pkg-config --libs --cflags gtk+-2.0)'
alias compileada='gnatmake -gnato -gnatv'
alias compclass='g++ $(pkg-config --cflags gtk+-2.0) -I ~/Cpp/classes_fournies -c'
alias compilecpp='bash /home/maethor/Cpp/compile'
alias jv='/usr/lib/jvm/java-6-sun/bin/java'
