#!/bin/zsh

###########
# Aliases #
###########

# Color & humain-readable
alias ls="ls --classify --tabsize=0 --literal --color=auto --show-control-chars --human-readable"
alias grep="grep --color=tty"
alias du="du --human-readable"
alias df="df -h"
[[ -x /usr/bin/pydf ]] && alias df="pydf -h"
[[ -x /usr/bin/htop ]] && alias top="htop"
[[ -x /usr/bin/colorgcc ]] && alias gcc="colorgcc"
[[ -x /usr/bin/colormake ]] && alias make="colormake"
[[ -x /usr/bin/aptitude ]] && alias aptitude="aptitude --disable-columns"

# Confirmation before overwriting a file
alias cp="cp --interactive"
alias mv="mv --interactive"
#alias rm="rm --interactive"

# 'ls' aliases
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias llm="ls -la | most"

# Misc Aliases
alias less="less --quiet"
alias m="mutt -y"
alias rsu="su -c zsh" 
if [ -x /usr/bin/sudo ] ; then alias rsu="sudo zsh" ; fi
alias shell="exec zsh"
alias slog="tail -n 60 /var/log/syslog"
alias mlog="tail -n 60 /var/log/mail.log"
alias nano="nano -miA"
alias cd..="cd .."
alias cleanup="rm -f *~"

# Compilation aliases
alias compilegtk='gcc $(pkg-config --libs --cflags gtk+-2.0)'
alias compileada="gnatmake -gnato -gnatv"
alias gcc99="gcc -std=c99"

# Editor
[[ -x /usr/bin/vim ]] && export EDITOR="vim"
alias e=$EDITOR

# Pager stuff
[[ -x /usr/bin/most ]] && export PAGER="most" && alias more="most" && alias less="most"

# Pip

PIP_BIN="`which pip`"
alias pip-sys="$PIP_BIN"

pip() {
    if [ -n "$VIRTUAL_ENV" ]
    then $PIP_BIN -E "$VIRTUAL_ENV" "$@"
    else echo "Not currently in a venv -- use pip-sys to work system-wide."
    fi
}
