#!/bin/zsh

export TEXMFHOME=$HOME/.texmf
export PATH=$PATH:$HOME/.bin
export WORKON_HOME=$HOME/.envs
export PROJECT_HOME=$HOME/.Programmes
if [ -e /usr/local/bin/virtualenvwrapper.sh ] 
    then source /usr/local/bin/virtualenvwrapper.sh
fi
case "$TERM" in
    rxvt-256color)
        TERM=rxvt-unicode
        ;;
    rxvt-unicode-256color)
        TERM=rxvt-unicode
        ;;
esac
