#!/bin/zsh

export TEXMFHOME=$HOME/.texmf
export PATH=$PATH:$HOME/.bin
export WORKON_HOME=$HOME/.envs
export PROJECT_HOME=$HOME/.Programmes
if [ -e /usr/local/bin/virtualenvwrapper.sh ] 
    then source /usr/local/bin/virtualenvwrapper.sh
fi
