#!/bin/zsh

export TEXMFHOME="$HOME/.texmf"
export PATH="$PATH:$HOME/.bin:$HOME/.local/bin"
export WORKON_HOME="$HOME/.envs"
export PROJECT_HOME="$HOME/Programmes/Work"
export PIP_DOWNLOAD_CACHE="$HOME/.pip/cache"
export PIP_VIRTUALENV_BASE=$WORKON_HOME

#export PATH=$PATH:/opt/node/bin
#export NODE_PATH=/opt/node:/opt/node/lib/node_modules

#if [ -e /usr/local/bin/virtualenvwrapper.sh ] 
#    then source /usr/local/bin/virtualenvwrapper.sh
#fi
case "$TERM" in
    #rxvt-256color)
        #TERM=rxvt-unicode
        #;;
    rxvt-unicode-256color)
        #TERM=rxvt-unicode
        TERM=rxvt-256color
        ;;
esac
