#!/bin/zsh
########################################
# Options de zsh (cf 'man zshoptions') #
########################################

# Je ne veux JAMAIS de beeps
unsetopt beep
unsetopt hist_beep
unsetopt list_beep

#unsetopt clobber		# >| doit être utilisés pour pouvoir écraser un fichier déjà existant ;
unsetopt ignore_eof		# Ctrl+D est équivalent à 'logout'
#setopt print_exit_value	# Affiche le code de sortie si différent de '0'
#unsetopt rm_star_silent	# Demande confirmation pour 'rm *'
#setopt correct			# Correction orthographique des commandes (Désactivé car, contrairement à ce que dit le "man", il essaye de corriger les commandes avant de les hasher)
setopt nullglob			# Si on utilise des jokers dans une liste d'arguments, retire les jokers qui ne correspondent à rien au lieu de donner une erreur
setopt auto_cd			# /usr/local est équivalent à cd /usr/local
setopt notify			# indique le status des taches de fond immédiatement

